<?php
  /** @var array $event */
  /** @var bool $isCompleted */
  /** @var array $user */
?>

<div class="card mb-4" style="background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); color: #fff; border: none;">
  <div class="card-body p-4 d-flex flex-wrap justify-content-between align-items-center gap-3">
    <div>
      <div class="d-flex align-items-center gap-2 mb-1">
        <a href="<?= e(url('/admin/reports')) ?>" class="text-white-50 text-decoration-none small">&larr; Back to Reports</a>
        <span class="text-white-50">&bull;</span>
        <span class="badge bg-<?= $isCompleted ? 'success' : 'warning text-dark' ?>"><?= e(strtoupper($event['status'] ?? 'draft')) ?></span>
      </div>
      <h2 class="h3 fw-bold mb-1 text-white">Final Event Institutional Report</h2>
      <p class="text-white-50 mb-0"><?= e($event['title']) ?></p>
    </div>
    <?php if ($isCompleted): ?>
      <div class="d-flex gap-2">
        <a href="<?= e(url('/admin/reports/event/' . $event['id'] . '/export?format=csv')) ?>" class="btn btn-outline-light btn-sm">
          <i class="bi bi-file-earmark-spreadsheet me-1"></i> Export Roster CSV
        </a>
        <button type="button" onclick="window.print()" class="btn btn-light btn-sm fw-semibold">
          <i class="bi bi-printer me-1"></i> Print / Save PDF
        </button>
      </div>
    <?php endif; ?>
  </div>
</div>

<?php if (!$isCompleted): ?>
  <!-- Pending Event Completion Notice -->
  <div class="card border-0 shadow-sm text-center py-5 px-4 my-4">
    <div class="card-body">
      <div class="display-4 text-warning mb-3">
        <i class="bi bi-hourglass-split"></i>
      </div>
      <h4 class="fw-bold text-dark mb-2">Final Event Report Pending Completion</h4>
      <p class="text-muted mx-auto" style="max-width: 600px;">
        This event is currently in <strong><?= e(ucfirst($event['status'] ?? 'active')) ?></strong> status.
        The certified Final Event Report with turnout percentages, hourly check-in timeline, attendee rosters, and certificate audits will automatically unlock once the event is marked as <strong>Completed</strong>.
      </p>
      <div class="mt-4 d-flex justify-content-center gap-3">
        <a href="<?= e(url('/admin/events/' . $event['id'])) ?>" class="btn btn-outline-primary btn-sm">
          <i class="bi bi-eye me-1"></i> View Event Details
        </a>
        <a href="<?= e(url('/admin/analytics/event/' . $event['id'])) ?>" class="btn btn-primary btn-sm">
          <i class="bi bi-graph-up me-1"></i> Live Real-Time Analytics
        </a>
      </div>
    </div>
  </div>
<?php else: ?>
  <!-- Completed Event Executive Report -->
  <!-- Event Summary Header -->
  <div class="card border-0 shadow-sm mb-4">
    <div class="card-body p-4">
      <div class="row g-3 align-items-center">
        <div class="col-md-8">
          <div class="d-flex align-items-center gap-2 text-muted small mb-1">
            <span><i class="bi bi-calendar3 me-1"></i> <?= e(date('F d, Y', strtotime((string) $event['start_time']))) ?></span>
            <span>&bull;</span>
            <span><i class="bi bi-clock me-1"></i> <?= e(date('h:i A', strtotime((string) $event['start_time']))) ?> - <?= e(date('h:i A', strtotime((string) $event['end_time']))) ?></span>
            <span>&bull;</span>
            <span class="badge bg-secondary"><?= e(strtoupper($event['event_type'] ?? 'offline')) ?></span>
          </div>
          <h4 class="fw-bold text-dark mb-2"><?= e($event['title']) ?></h4>
          <p class="text-muted small mb-0">
            <strong>Venue:</strong> <?= e($event['venue_name'] ?? 'N/A') ?> 
            <?php if (!empty($event['venue_address'])): ?>
              &bull; <?= e($event['venue_address']) ?>
            <?php endif; ?>
          </p>
          <?php if (!empty($event['collaboration_with'])): ?>
            <p class="text-primary small fw-semibold mt-1 mb-0">
              <i class="bi bi-handshake me-1"></i> In Collaboration with: <?= e($event['collaboration_with']) ?>
            </p>
          <?php endif; ?>
        </div>
        <div class="col-md-4 text-md-end border-start">
          <div class="text-muted small">Certified Report Generated On:</div>
          <div class="fw-bold text-dark"><?= e(date('F d, Y — h:i A')) ?></div>
          <div class="small text-muted mt-1">Generated by: <?= e($user['name'] ?? 'Administrator') ?></div>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Metrics Row -->
  <div class="row g-3 mb-4">
    <div class="col-6 col-md-3">
      <div class="card border-0 shadow-sm text-center p-3 h-100">
        <div class="text-muted small text-uppercase fw-semibold">Total Registrations</div>
        <div class="display-6 fw-bold text-primary my-1"><?= number_format($total_registrations ?? 0) ?></div>
        <div class="small text-muted">Signed Up</div>
      </div>
    </div>
    <div class="col-6 col-md-3">
      <div class="card border-0 shadow-sm text-center p-3 h-100">
        <div class="text-muted small text-uppercase fw-semibold">Verified Check-Ins</div>
        <div class="display-6 fw-bold text-success my-1"><?= number_format($checked_in_count ?? 0) ?></div>
        <div class="small text-success fw-semibold">Attended</div>
      </div>
    </div>
    <div class="col-6 col-md-3">
      <div class="card border-0 shadow-sm text-center p-3 h-100">
        <div class="text-muted small text-uppercase fw-semibold">Turnout Rate</div>
        <div class="display-6 fw-bold text-info my-1"><?= e($attendance_rate ?? 0) ?>%</div>
        <div class="small text-muted">Attendance Yield</div>
      </div>
    </div>
    <div class="col-6 col-md-3">
      <div class="card border-0 shadow-sm text-center p-3 h-100">
        <div class="text-muted small text-uppercase fw-semibold">Certificates Issued</div>
        <div class="display-6 fw-bold text-warning my-1"><?= number_format($certificates_count ?? 0) ?></div>
        <div class="small text-muted">Active Credentials</div>
      </div>
    </div>
  </div>

  <!-- Breakdown Cards Row -->
  <div class="row g-4 mb-4">
    <!-- Category Breakdown -->
    <div class="col-md-6">
      <div class="card border-0 shadow-sm h-100">
        <div class="card-header bg-white py-3 border-bottom">
          <h6 class="card-title fw-bold mb-0 text-dark">Participant Category Distribution</h6>
        </div>
        <div class="card-body p-3">
          <?php if (empty($categories)): ?>
            <div class="text-muted text-center py-3 small">No category telemetry available.</div>
          <?php else: ?>
            <div class="d-flex flex-column gap-2">
              <?php foreach ($categories as $cat): 
                $pct = $total_registrations > 0 ? round(((int)$cat['count'] / $total_registrations) * 100, 1) : 0;
              ?>
                <div>
                  <div class="d-flex justify-content-between small mb-1">
                    <span class="fw-semibold"><?= e(ucfirst($cat['category'])) ?></span>
                    <span class="text-muted"><?= (int) $cat['count'] ?> (<?= $pct ?>%)</span>
                  </div>
                  <div class="progress" style="height: 6px;">
                    <div class="progress-bar bg-primary" style="width: <?= $pct ?>%"></div>
                  </div>
                </div>
              <?php endforeach; ?>
            </div>
          <?php endif; ?>
        </div>
      </div>
    </div>

    <!-- Device Platform Breakdown -->
    <div class="col-md-6">
      <div class="card border-0 shadow-sm h-100">
        <div class="card-header bg-white py-3 border-bottom">
          <h6 class="card-title fw-bold mb-0 text-dark">Acquisition Platforms (Devices)</h6>
        </div>
        <div class="card-body p-3">
          <?php if (empty($devices)): ?>
            <div class="text-muted text-center py-3 small">No platform telemetry available.</div>
          <?php else: ?>
            <div class="d-flex flex-column gap-2">
              <?php foreach ($devices as $dev): 
                $pct = $total_registrations > 0 ? round(((int)$dev['count'] / $total_registrations) * 100, 1) : 0;
              ?>
                <div>
                  <div class="d-flex justify-content-between small mb-1">
                    <span class="fw-semibold"><?= e(ucfirst($dev['device_type'])) ?></span>
                    <span class="text-muted"><?= (int) $dev['count'] ?> (<?= $pct ?>%)</span>
                  </div>
                  <div class="progress" style="height: 6px;">
                    <div class="progress-bar bg-info" style="width: <?= $pct ?>%"></div>
                  </div>
                </div>
              <?php endforeach; ?>
            </div>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>

  <!-- Participant Roster Table -->
  <div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white py-3 border-bottom d-flex justify-content-between align-items-center">
      <h5 class="card-title fw-bold mb-0 text-dark">Participant Attendance Roster</h5>
      <span class="badge bg-light text-dark"><?= count($roster ?? []) ?> Records</span>
    </div>
    <div class="table-responsive">
      <table class="table table-hover align-middle mb-0">
        <thead class="table-light small">
          <tr>
            <th>Reg Code</th>
            <th>Attendee Name</th>
            <th>Contact (Masked)</th>
            <th>Category</th>
            <th>Status</th>
            <th>Check-in Time</th>
            <th>Method</th>
            <th>Certificate ID</th>
          </tr>
        </thead>
        <tbody class="small">
          <?php if (empty($roster)): ?>
            <tr>
              <td colspan="8" class="text-center py-4 text-muted">No registration records found for this event.</td>
            </tr>
          <?php else: ?>
            <?php foreach ($roster as $row): 
              $isAttended = ($row['attendance_status'] ?? '') === 'attended';
            ?>
              <tr>
                <td><code><?= e($row['registration_code']) ?></code></td>
                <td class="fw-semibold text-dark"><?= e($row['full_name']) ?></td>
                <td class="text-muted font-monospace small"><?= e($row['phone_masked'] ?? '***') ?></td>
                <td><span class="badge bg-light text-dark border"><?= e(ucfirst($row['category'] ?? 'General')) ?></span></td>
                <td>
                  <?php if ($isAttended): ?>
                    <span class="badge bg-success">Attended</span>
                  <?php else: ?>
                    <span class="badge bg-secondary">Absent</span>
                  <?php endif; ?>
                </td>
                <td>
                  <?= !empty($row['attended_at']) ? e(date('h:i A', strtotime((string)$row['attended_at']))) : '<span class="text-muted">—</span>' ?>
                </td>
                <td>
                  <?php if (!empty($row['check_in_method'])): ?>
                    <span class="badge bg-light text-secondary border">
                      <?= e(strtoupper($row['check_in_method'])) ?>
                      <?php if (!empty($row['checkin_geofence_verified'])): ?>
                        <i class="bi bi-geo-alt-fill text-success" title="Geofence GPS Verified"></i>
                      <?php endif; ?>
                    </span>
                  <?php else: ?>
                    <span class="text-muted">—</span>
                  <?php endif; ?>
                </td>
                <td>
                  <?php if (!empty($row['certificate_number'])): ?>
                    <a href="<?= e(url('/verify/' . $row['certificate_number'])) ?>" target="_blank" class="text-decoration-none">
                      <code><?= e($row['certificate_number']) ?></code>
                    </a>
                  <?php else: ?>
                    <span class="text-muted">—</span>
                  <?php endif; ?>
                </td>
              </tr>
            <?php endforeach; ?>
          <?php endif; ?>
        </tbody>
      </table>
    </div>
  </div>
<?php endif; ?>
